from PyQt5 import QtWidgets, QtCore, QtGui
from pyqtgraph import PlotWidget, plot
from TempGraph import Graph


class Ui_TempCont(object):
    def setupUi(self, TempCont):
        TempCont.setObjectName("Temperature Controller")
        TempCont.resize(787, 223)
        self.SetpointLabel = QtWidgets.QLabel(TempCont)
        self.SetpointLabel.setGeometry(QtCore.QRect(40, 10, 81, 41))
        self.SetpointLabel.setObjectName("SetpointLabel")
        self.SetpointTextEdit = QtWidgets.QTextEdit(TempCont)
        self.SetpointTextEdit.setGeometry(QtCore.QRect(110, 20, 61, 21))
        self.SetpointTextEdit.setObjectName("SetpointTextEdit")
        self.SetSetPointButton = QtWidgets.QPushButton(TempCont)
        self.SetSetPointButton.setGeometry(QtCore.QRect(180, 20, 51, 23))
        self.SetSetPointButton.setObjectName("SetSetPointButton")
        self.StartRate = QtWidgets.QPushButton(TempCont)
        self.StartRate.setGeometry(QtCore.QRect(80, 170, 75, 23))
        self.StartRate.setObjectName("StartRate")
        self.StopRate = QtWidgets.QPushButton(TempCont)
        self.StopRate.setGeometry(QtCore.QRect(180, 170, 75, 23))
        self.StopRate.setObjectName("StopRate")
        self.StartTextEdit = QtWidgets.QTextEdit(TempCont)
        self.StartTextEdit.setGeometry(QtCore.QRect(20, 140, 81, 21))
        self.StartTextEdit.setObjectName("StartTextEdit")
        self.EndTextEdit = QtWidgets.QTextEdit(TempCont)
        self.EndTextEdit.setGeometry(QtCore.QRect(130, 140, 71, 21))
        self.EndTextEdit.setObjectName("EndTextEdit")
        self.RateTextEdit = QtWidgets.QTextEdit(TempCont)
        self.RateTextEdit.setGeometry(QtCore.QRect(230, 140, 81, 21))
        self.RateTextEdit.setObjectName("RateTextEdit")
        self.StartLabel = QtWidgets.QLabel(TempCont)
        self.StartLabel.setGeometry(QtCore.QRect(50, 120, 71, 16))
        self.StartLabel.setObjectName("StartLabel")
        self.EndLabel = QtWidgets.QLabel(TempCont)
        self.EndLabel.setGeometry(QtCore.QRect(150, 120, 47, 13))
        self.EndLabel.setObjectName("EndLabel")
        self.RateLabel = QtWidgets.QLabel(TempCont)
        self.RateLabel.setGeometry(QtCore.QRect(250, 110, 41, 31))
        self.RateLabel.setObjectName("RateLabel")
        self.TargetTempLabel = QtWidgets.QLabel(TempCont)
        self.TargetTempLabel.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.TargetTempLabel.setObjectName("TargetTempLabel")
        self.HeaterOutLabel = QtWidgets.QLabel(TempCont)
        self.HeaterOutLabel.setGeometry(QtCore.QRect(120, 50, 71, 21))
        self.HeaterOutLabel.setObjectName("HeaterOutLabel")
        self.CurrentTempLabel = QtWidgets.QLabel(TempCont)
        self.CurrentTempLabel.setGeometry(QtCore.QRect(220, 50, 121, 21))
        self.CurrentTempLabel.setObjectName("CurrentTempLabel")
        self.textBrowser = QtWidgets.QTextBrowser(TempCont)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 71, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(TempCont)
        self.textBrowser_2.setGeometry(QtCore.QRect(120, 70, 81, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(TempCont)
        self.textBrowser_3.setGeometry(QtCore.QRect(230, 70, 81, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.TempGraph = Graph(parent=TempCont)
        self.TempGraph.setGeometry(QtCore.QRect(330, 10, 441, 201))
        self.TempGraph.setObjectName("TempGraph")

        self.retranslateUi(TempCont)
        QtCore.QMetaObject.connectSlotsByName(TempCont)

    def retranslateUi(self, TempCont):
        _translate = QtCore.QCoreApplication.translate
        TempCont.setWindowTitle(_translate("TempCont", "TempCont"))
        self.SetpointLabel.setText(_translate("TempCont", "<html><head/><body><p><span style=\" font-size:12pt;\">Setpoint:</span></p></body></html>"))
        self.SetSetPointButton.setText(_translate("TempCont", "Set"))
        self.StartRate.setText(_translate("TempCont", "Start"))
        self.StopRate.setText(_translate("TempCont", "Stop"))
        self.StartLabel.setText(_translate("TempCont", "Start"))
        self.EndLabel.setText(_translate("TempCont", "End"))
        self.RateLabel.setText(_translate("TempCont", "Rate"))
        self.TargetTempLabel.setText(_translate("TempCont", "Target Temperature"))
        self.HeaterOutLabel.setText(_translate("TempCont", "Heater Output"))
        self.CurrentTempLabel.setText(_translate("TempCont", "Current Temperature"))
        



